[package]
name = "graphome"
version = "0.1.0"
edition = "2021"

[lib]
name = "graphome"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
bitvec = "1.0"
rayon = "1.5"
csv = "1.1"
termcolor = "1.1"
palette = "0.6"
nalgebra = "0.33.0"
tempfile = "3.3"
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-linalg = { version = "0.16.0", features = ["openblas-src"] }
openblas-src = "0.7.17"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
