[package]
name = "graphome"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
indicatif = "0.17"
bitvec = "1.0"
rayon = "1.5"
csv = "1.1"
termcolor = "1.1"
palette = "0.6"
nalgebra = "0.33.0"
tempfile = "3.3"
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-linalg = "0.16.0"
lapack = "0.19.0"

[build-dependencies]
cmake = "0.1"
curl = "0.4.47"

[lib]
name = "graphome"
path = "src/lib.rs"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-Wl,-rpath,./lapack/build"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,./lapack/build"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-rpath,./lapack/build"]
